name: Node.js Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: |
          node -v
          npm install
          npm run build --if-present

      - run: |
          node -v
          npm ci
          npm run build
          sudo pm2 restart imageBackend

