name: Node.js Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
       # Cache dependencies step
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm # npm cache directory
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
      
            
      - name: Check Node.js version
        run: node -v
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - run: |
          npm ci


      - name: Check if pm2 process exists
        id: check-pm2
        run: |
          if pm2 show imageBackend; then
            echo "::set-output name=pm2_running::true"
          else
            echo "::set-output name=pm2_running::false"
          fi

      # Stop the pm2 process if it's running
      - name: Stop pm2 process if running
        if: steps.check-pm2.outputs.pm2_running == 'true'
        run: pm2 stop imageBackend

      # Start the pm2 process
      - name: Start pm2 process
        if: steps.check-pm2.outputs.pm2_running == 'false'
        run: pm2 start imageBackend --update-env

      - run: |
          pm2 save






